//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillCharge
    {
        public System.Guid BillChargeId { get; set; }
        public System.Guid BillSetUpId { get; set; }
        public System.Guid AccountId { get; set; }
        public int Method { get; set; }
        public double Rate { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual BillSetUp BillSetUp { get; set; }
        public virtual BillSetUp BillSetUp1 { get; set; }
        public virtual Ledger Ledger1 { get; set; }
    }
}
