//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillSetUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillSetUp()
        {
            this.BillCharges = new HashSet<BillCharge>();
            this.BillCharges1 = new HashSet<BillCharge>();
        }
    
        public System.Guid BillSetUpId { get; set; }
        public int PremisesType { get; set; }
        public Nullable<int> AreaFrom { get; set; }
        public Nullable<int> AreaUpTo { get; set; }
        public Nullable<bool> BillGenerated { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<System.DateTime> GenerateDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> InterestApplicable { get; set; }
        public Nullable<long> BillSetUpNo { get; set; }
        public Nullable<double> PropertyTax { get; set; }
        public Nullable<double> MaintananceCharges { get; set; }
        public Nullable<double> ParkingCharges { get; set; }
        public Nullable<double> RepairFundCollection { get; set; }
        public Nullable<double> SinkingFundCharges { get; set; }
        public Nullable<double> WaterCharges { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillCharge> BillCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillCharge> BillCharges1 { get; set; }
    }
}
