//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classified
    {
        public System.Guid ClassifiedId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string Categories { get; set; }
        public Nullable<int> Type { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Condition { get; set; }
        public string BrandName { get; set; }
        public string Amount { get; set; }
        public string FileName1 { get; set; }
    }
}
