//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeEmployeeMapping
    {
        public System.Guid CommitteeEmployeeMappingId { get; set; }
        public Nullable<System.Guid> CommitteeId { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<System.Guid> DesignationId { get; set; }
    }
}
