//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentOnDiscussion
    {
        public System.Guid CommentId { get; set; }
        public Nullable<System.Guid> DiscussionId { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
    }
}
