//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintRespons
    {
        public System.Guid ComplaintResponseId { get; set; }
        public int ComplaintStatus { get; set; }
        public System.DateTime AttendedTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> AttendedById { get; set; }
        public Nullable<System.Guid> ComplaintId { get; set; }
    }
}
