//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreUser
    {
        public System.Guid CoreUserId { get; set; }
        public string CoreEmail { get; set; }
        public string CoreUserName { get; set; }
        public string CorePassword { get; set; }
        public Nullable<System.Guid> RightTypeId { get; set; }
    
        public virtual RightsType RightsType { get; set; }
        public virtual RightsType RightsType1 { get; set; }
    }
}
