//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreMember
    {
        public System.Guid MemberId { get; set; }
        public string CoreDesignation { get; set; }
        public System.Guid FlatId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int MaritalStatus { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string PermanentAddress { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string LandLineNo1 { get; set; }
        public string InterComNo { get; set; }
        public Nullable<System.Guid> CoreUserId { get; set; }
        public Nullable<System.Guid> CommitteeId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<int> Status { get; set; }
        public string Gender { get; set; }
        public string MemberNo { get; set; }
        public string IdProof { get; set; }
        public string IdNo { get; set; }
    }
}
