//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreVisitor
    {
        public System.Guid VisitorId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string PersonToMeet { get; set; }
        public string Vehical { get; set; }
        public string VehicalNumber { get; set; }
        public System.DateTime EntryTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string Work { get; set; }
        public Nullable<System.Guid> FlatId { get; set; }
        public string PictureLocation { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public string relation { get; set; }
        public string IDNo { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> IDProof { get; set; }
    }
}
