//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreRight
    {
        public System.Guid CoreRightId { get; set; }
        public string RightName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.Guid> ParentRightId { get; set; }
        public Nullable<int> MenuType { get; set; }
        public Nullable<System.Guid> DashboardId { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<int> IsOnDashBoard { get; set; }
        public Nullable<int> DashBoardNumber { get; set; }
    }
}
