//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitCreditNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DebitCreditNote()
        {
            this.DebitCreditNoteEntries = new HashSet<DebitCreditNoteEntry>();
            this.DebitCreditNoteEntries1 = new HashSet<DebitCreditNoteEntry>();
            this.DebitCreditNoteEntries2 = new HashSet<DebitCreditNoteEntry>();
        }
    
        public System.Guid DebitCreditNoteId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitCreditNoteEntry> DebitCreditNoteEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitCreditNoteEntry> DebitCreditNoteEntries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitCreditNoteEntry> DebitCreditNoteEntries2 { get; set; }
        public virtual DebitCreditNote DebitCreditNote1 { get; set; }
        public virtual DebitCreditNote DebitCreditNote2 { get; set; }
        public virtual DebitCreditNote DebitCreditNote11 { get; set; }
        public virtual DebitCreditNote DebitCreditNote3 { get; set; }
    }
}
