//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ParentName { get; set; }
        public string PermanentAddress { get; set; }
        public string CurrentAddress { get; set; }
        public string ContactNo1 { get; set; }
        public string ContactNo2 { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string Qualification { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public Nullable<System.DateTime> DateOfRelease { get; set; }
        public Nullable<int> Type { get; set; }
        public string AgencyName { get; set; }
        public Nullable<System.Guid> DesignationId { get; set; }
        public Nullable<System.Guid> CoreUserId { get; set; }
        public string MonthsofAttendance { get; set; }
        public string NoofdaysAbsent { get; set; }
    }
}
