//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAgency
    {
        public System.Guid EmployeeAgencyID { get; set; }
        public string AgencyName { get; set; }
        public string AgencyAddress { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string PhNo { get; set; }
        public string ContactPerson { get; set; }
        public string BankAccountNo { get; set; }
        public string ContactBasisAs { get; set; }
    }
}
