//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enquiry()
        {
            this.EnquiryForServices = new HashSet<EnquiryForService>();
        }
    
        public System.Guid EnquiryId { get; set; }
        public string Name { get; set; }
        public string OrganisationName { get; set; }
        public string OrganisationAddress { get; set; }
        public string Designation { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryForService> EnquiryForServices { get; set; }
    }
}
