//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMemberDetail
    {
        public System.Guid FamilyMemberId { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Relation { get; set; }
        public string Email { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public string MemberPassword { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string LastName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Gender { get; set; }
        public string Profession { get; set; }
        public string hobby { get; set; }
    }
}
