//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public System.Guid FlatId { get; set; }
        public string FlatNo { get; set; }
        public string FlatArea { get; set; }
        public string Floor { get; set; }
        public Nullable<double> MaintainanceCharge { get; set; }
        public Nullable<System.Guid> WingId { get; set; }
        public Nullable<System.Guid> MemberAccountId { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<double> PropertyTax { get; set; }
        public Nullable<double> MaintananceCharges { get; set; }
        public Nullable<double> ParkingCharges { get; set; }
        public Nullable<double> RepairFundCollection { get; set; }
        public Nullable<double> SinkingFundCharges { get; set; }
        public Nullable<double> WaterCharges { get; set; }
        public Nullable<double> NonOccupancyCharges { get; set; }
    }
}
