//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Housekeepingstaff
    {
        public System.Guid HousekeepingstaffID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string PictureLocation { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public string Gender { get; set; }
        public string SocietyDOJ { get; set; }
        public string WorkingflatNum { get; set; }
        public string DateofEntry { get; set; }
    }
}
