//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Income()
        {
            this.TransactionRows = new HashSet<TransactionRow>();
            this.TransactionRows1 = new HashSet<TransactionRow>();
        }
    
        public System.Guid IncomeId { get; set; }
        public string IncomeNo { get; set; }
        public System.DateTime DateOfIncome { get; set; }
        public Nullable<System.Guid> IncomeFromId { get; set; }
        public Nullable<System.Guid> ToAccountId { get; set; }
        public int PaymentMode { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeNo { get; set; }
        public string IssuingBank { get; set; }
        public Nullable<System.DateTime> ReconcileDate { get; set; }
        public Nullable<System.DateTime> RevertDate { get; set; }
        public string Description { get; set; }
        public double Amount { get; set; }
        public Nullable<int> PaymentOption { get; set; }
        public Nullable<double> IncomeAmount { get; set; }
        public Nullable<double> InterestAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRow> TransactionRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRow> TransactionRows1 { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual Ledger Ledger1 { get; set; }
        public virtual Ledger Ledger2 { get; set; }
        public virtual Ledger Ledger3 { get; set; }
    }
}
