//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentDetail
    {
        public System.Guid InstrumentDetailId { get; set; }
        public Nullable<int> InstrumentType { get; set; }
        public string InstrumentNumber { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public string InstrumentSource { get; set; }
        public Nullable<double> InstrumentAmount { get; set; }
        public Nullable<System.Guid> PaymentDetailId { get; set; }
        public Nullable<int> EntryType { get; set; }
        public string InvoiceNo { get; set; }
    }
}
