//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public System.Guid JournalEntryId { get; set; }
        public System.Guid JournalId { get; set; }
        public System.Guid LedgerId { get; set; }
        public int DebitCredit { get; set; }
        public double Principal { get; set; }
        public double Interest { get; set; }
        public string Narration { get; set; }
        public string AccountId { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Journal Journal { get; set; }
        public virtual Journal Journal1 { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual Ledger Ledger1 { get; set; }
    }
}
