//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageEmployee
    {
        public System.Guid EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.Guid> DesignationId { get; set; }
        public Nullable<System.Guid> EmployeeAgencyID { get; set; }
        public string DateofJoin { get; set; }
        public string ImagePath { get; set; }
        public string ImagePath1 { get; set; }
        public string ImagePath2 { get; set; }
        public Nullable<long> EmployeeSalary { get; set; }
        public Nullable<System.Guid> CoreUserId { get; set; }
    }
}
