//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public System.Guid PaymentDetailId { get; set; }
        public Nullable<int> PaymentYear { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<int> PaymentMonth { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.Guid> FlatId { get; set; }
        public Nullable<System.Guid> MemberAccountId { get; set; }
    }
}
