//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.BillReceipts = new HashSet<BillReceipt>();
            this.BillReceives = new HashSet<BillReceive>();
            this.BillReceives1 = new HashSet<BillReceive>();
            this.TransactionRows = new HashSet<TransactionRow>();
            this.TransactionRows1 = new HashSet<TransactionRow>();
        }
    
        public System.Guid ReceiptId { get; set; }
        public string ReceiptNo { get; set; }
        public int PaymentMode { get; set; }
        public Nullable<System.Guid> ReceiptFromId { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeNo { get; set; }
        public string IssuingBank { get; set; }
        public Nullable<System.DateTime> ReconcileDate { get; set; }
        public Nullable<System.DateTime> RevertDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ReceiveInId { get; set; }
        public Nullable<double> ExtraAmount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> InterestAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReceipt> BillReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReceive> BillReceives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReceive> BillReceives1 { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual Ledger Ledger1 { get; set; }
        public virtual Ledger Ledger2 { get; set; }
        public virtual Ledger Ledger3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRow> TransactionRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRow> TransactionRows1 { get; set; }
    }
}
