//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEEntities : DbContext
    {
        public SEEntities()
            : base("name=SEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillCharge> BillCharges { get; set; }
        public virtual DbSet<BillReceipt> BillReceipts { get; set; }
        public virtual DbSet<BillReceive> BillReceives { get; set; }
        public virtual DbSet<BillSetUp> BillSetUps { get; set; }
        public virtual DbSet<CommitteeMemberMapping> CommitteeMemberMappings { get; set; }
        public virtual DbSet<DebitCreditNote> DebitCreditNotes { get; set; }
        public virtual DbSet<DebitCreditNoteEntry> DebitCreditNoteEntries { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<EnquiryForService> EnquiryForServices { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoicePayment> InvoicePayments { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<JournalEntry> JournalEntries { get; set; }
        public virtual DbSet<Ledger> Ledgers { get; set; }
        public virtual DbSet<Narration> Narrations { get; set; }
        public virtual DbSet<OpeningBalance> OpeningBalances { get; set; }
        public virtual DbSet<OpeningBankReco> OpeningBankRecoes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<RightsMapping> RightsMappings { get; set; }
        public virtual DbSet<RightsType> RightsTypes { get; set; }
        public virtual DbSet<ShoutBox> ShoutBoxes { get; set; }
        public virtual DbSet<SocietyBase> SocietyBases { get; set; }
        public virtual DbSet<SpecificAccount> SpecificAccounts { get; set; }
        public virtual DbSet<SpecificGroup> SpecificGroups { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<TransactionRow> TransactionRows { get; set; }
        public virtual DbSet<Vehical> Vehicals { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Amenity> Amenities { get; set; }
        public virtual DbSet<Classified> Classifieds { get; set; }
        public virtual DbSet<CommentOnDiscussion> CommentOnDiscussions { get; set; }
        public virtual DbSet<Committee> Committees { get; set; }
        public virtual DbSet<CommitteeEmployeeMapping> CommitteeEmployeeMappings { get; set; }
        public virtual DbSet<ComplaintRespons> ComplaintResponses { get; set; }
        public virtual DbSet<CoreDesignation> CoreDesignations { get; set; }
        public virtual DbSet<CoreMember> CoreMembers { get; set; }
        public virtual DbSet<CoreRight> CoreRights { get; set; }
        public virtual DbSet<CoreSupport> CoreSupports { get; set; }
        public virtual DbSet<CoreUser> CoreUsers { get; set; }
        public virtual DbSet<CoreVisitor> CoreVisitors { get; set; }
        public virtual DbSet<Dashboard> Dashboards { get; set; }
        public virtual DbSet<DashboardColumn> DashboardColumns { get; set; }
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeAgency> EmployeeAgencies { get; set; }
        public virtual DbSet<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FamilyMemberDetail> FamilyMemberDetails { get; set; }
        public virtual DbSet<Flat> Flats { get; set; }
        public virtual DbSet<Housekeepingstaff> Housekeepingstaffs { get; set; }
        public virtual DbSet<ImportantLink> ImportantLinks { get; set; }
        public virtual DbSet<InstrumentDetail> InstrumentDetails { get; set; }
        public virtual DbSet<Law> Laws { get; set; }
        public virtual DbSet<Maintanance> Maintanances { get; set; }
        public virtual DbSet<ManageEmployee> ManageEmployees { get; set; }
        public virtual DbSet<MemberAccount> MemberAccounts { get; set; }
        public virtual DbSet<Parking> Parkings { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<PollingOption> PollingOptions { get; set; }
        public virtual DbSet<Rfq> Rfqs { get; set; }
        public virtual DbSet<Society> Societies { get; set; }
        public virtual DbSet<TrialBalance> TrialBalances { get; set; }
        public virtual DbSet<UploadedFile> UploadedFiles { get; set; }
        public virtual DbSet<UserRightMapping> UserRightMappings { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Wing> Wings { get; set; }
    }
}
