//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society
    {
        public System.Guid SocietyId { get; set; }
        public string SocietyName { get; set; }
        public string SocietyAddress { get; set; }
        public string ContactDetails { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
    }
}
