//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyBase
    {
        public System.Guid SocietyBaseId { get; set; }
        public string SocietyName { get; set; }
        public string SocietyAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string Country { get; set; }
        public string RegistrationNo { get; set; }
        public string Abbreviation { get; set; }
        public string TelephoneNo { get; set; }
        public string FaxNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string ConsultancyName { get; set; }
        public string ConsultancyContactNo { get; set; }
        public Nullable<double> AuthoriseCapitalPreviousYear { get; set; }
        public Nullable<double> AuthoriseCapitalCurrentYear { get; set; }
        public string Description { get; set; }
        public string FirstFinancialYear { get; set; }
        public string Chairman { get; set; }
        public string Secretary { get; set; }
        public string Treasurer { get; set; }
        public string BillAuthoriseSignatury { get; set; }
        public string ReceiptAuthoriseSignatury { get; set; }
        public string CAFirmName { get; set; }
        public string CAName { get; set; }
        public string CADesignation { get; set; }
        public string CARegistrationNo { get; set; }
        public double InterestRate { get; set; }
        public int InterestType { get; set; }
        public int InterestBasedOn { get; set; }
        public int RoundOff { get; set; }
        public int CreditMethod { get; set; }
        public bool PrintZeroAmount { get; set; }
        public int BillingFrequency { get; set; }
    }
}
