//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecificGroup()
        {
            this.Ledgers = new HashSet<Ledger>();
            this.Ledgers1 = new HashSet<Ledger>();
        }
    
        public System.Guid SpecificGroupId { get; set; }
        public string AccountType { get; set; }
        public Nullable<System.Guid> DebitGroupId { get; set; }
        public Nullable<System.Guid> CreditGroupId { get; set; }
    
        public virtual AccountGroup AccountGroup { get; set; }
        public virtual AccountGroup AccountGroup1 { get; set; }
        public virtual AccountGroup AccountGroup2 { get; set; }
        public virtual AccountGroup AccountGroup3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ledger> Ledgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ledger> Ledgers1 { get; set; }
    }
}
