//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public System.Guid TenantId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string maritalStatus { get; set; }
        public string Email { get; set; }
        public string JoiningDate { get; set; }
        public string ContractDuration { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> FlatId { get; set; }
        public string PhImagePath { get; set; }
        public string IdImagePath1 { get; set; }
        public string IdImagePath2 { get; set; }
        public Nullable<System.Guid> CoreUserId { get; set; }
        public string ContactNum { get; set; }
    }
}
