//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRightMapping
    {
        public System.Guid UserRightMappingId { get; set; }
        public Nullable<System.Guid> CoreUserId { get; set; }
        public Nullable<System.Guid> CoreRightId { get; set; }
        public Nullable<System.Guid> ParentUserRightId { get; set; }
    }
}
