//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGO.FDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehical
    {
        public System.Guid VehicalId { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public string VehicalType { get; set; }
        public string Colour { get; set; }
        public string VehicalNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime RegistrationValidityDate { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.Guid> FlatId { get; set; }
    }
}
